services:
  api:
    build: ./app
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
    networks:
      - employee_net1
    depends_on:
      - sqldb
      - nosqldb

  sqldb:
    image: postgres:16.15
    container_name: employee_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    networks:
      - employee_net1
    volumes:
      - db_data:/var/lib/postgresql/data

  nosqldb:
    image: mongo:latest
    container_name: employee_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: employee
    ports:
      - "27018:27017"
    networks:
      - employee_net1
    volumes:
      - nossql_data:/data/db
  nginx:
    build: ./nginx
    container_name: reverse_proxy_for_empapp
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - api
      - sqldb
      - nosqldb
    networks:
      - employee_net1
volumes:
  db_data:
    external: true

  nossql_data:
    external: true
networks:
  employee_net1:
    external: true