name: Integration Pipeline(CI)
on:
  push:
    branches: [ "legacy" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        ports:
          - 5432:5432
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    env:
        POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        # MONGO_USER: ${{secrets.MONGO_USER}}
        # MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Testing the code 
      run: pytest