name: Integration Pipeline(CI)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted,linux,wsl1]
    env:
        POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        MONGO_USER: ${{secrets.MONGO_USER}}
        MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
        NGINX_PORT: ${{secrets.NGINX_PORT}}
    steps:
    - uses: actions/checkout@v4
    - name: Sonarqube Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        SONAR_HOST_URL: ${{secrets.SONAR_TOKEN}}

    - name: Start Podman socket
      run: |
        systemctl --user enable --now podman.socket
        podman info
    - name: Create the volume db_data
      run: podman volume create db_data
    - name: Create the volume nossql_data
      run: podman volume create nossql_data
    - name: Create the Network
      run: podman network create --driver bridge --subnet 185.0.0.0/16 employee_net1
    - name: Build The Image
      run: podman compose build
    - name: Up the containers
      run:  podman compose up -d
    - name: check the running contaienrs
      run: podman compose ps
    - name: Down the containers
      run: podman compose down
  
    