name: Integration Pipeline(CI)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        MONGO_USER: ${{secrets.MONGO_USER}}
        MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
        NGINX_PORT: ${{secrets.NGINX_PORT}}
    steps:
    - uses: actions/checkout@v4
    - name: Create the volume db_data
      run: docker volume create db_data
    - name: Create the volume nossql_data
      run: docker volume create nossql_data
    - name: Create the Network
      run: docker network create --driver bridge --subnet 185.0.0.0/16 employee_net1
    - name: Build The Image
      run: docker compose build
    - name: Up the containers
      run:  docker compose up -d
    - name: check the running contaienrs
      run: docker compose ps
    - name: Down the containers
      run: docker compose down
    